#!/bin/bash
#SBATCH -p gpu_shared
#SBATCH --gpus=1
#SBATCH --job-name=gnn_ppo
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=06:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

#module purge
#module load 2021
#module load Anaconda3/2021.05
__conda_setup="$('/home/weerdr/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/weerdr/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/weerdr/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/weerdr/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

cd $HOME/simmodel/scripts/jobfiles
conda activate rlcourse
python test_gpu.py